### ISSUE TITLE
./gradlew assembleDebug failed for task ':app:externalNativeBuildDebug'

### ISSUE THREAD

**Issue by lambsteak** [pvallet/hello-sdl2-android#2]
Hi. I was trying to compile your project and when running gradlew I ran into this error:

Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /home/user/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/user/gamedev_android/hello-sdl2-android/android/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target main}
  ninja: error: '../../../../../distribution/android/SDL2/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libSDL2.so', needed by '../../../../../distribution/android/app/intermediates/cmake/debug/obj/armeabi-v7a/libmain.so', missing and no known rule to make it

**Comment by pvallet** [comment]
Hello, sorry for getting back to you so late, but if this still happening, would you have some info about which SDK version and which build tools version you have?
The only way I was able to get this error was by commenting out the line `compile project(':SDL2')` in `android/app/build.gradle`. I'm not sure what causes SDL not to be built.
Are you using the command line, or Android Studio? Are you on Linux?

**Comment by pvallet** [comment]
Closing as completed as the project has been upgraded a few times, feel free to reopen if this is still happening
